### PR TITLE
Let's be fancy and use the short array syntax (PHP >=5.4)

### PR DESCRIPTION
**Pull request by hiddeco**

### CODE REVIEW

**Comment by greggilbert** [comment]
Is this really necessary?

**Comment by hiddeco** [comment]
@greggilbert: it's used by all Laravel's core config files, looks cleaner and is shorter. So I would say, yes.

**Comment by greggilbert** [comment]
Not really feeling it, TBH. It's not hurting anyone.

**Comment by hiddeco** [comment]
Not even 9fec7ef? This is just invalid HTML, has nothing to do with preferences and hurts while validating a page it's used on.

**Comment by hiddeco** [comment]
@greggilbert: Also I would argue that despite your feelings, the package should follow the [PSR-2 coding style guide](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md) as described by the [Laravel 5.1 release notes](http://laravel.com/docs/5.1/releases#laravel-5.1). The [ ] short array syntax is de-facto standard according to [chapter 4.3](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md#43-methods) in this style guide.

**Comment by hiddeco** [comment]
Merge #82 instead.

**Pull request closed without merging**
