### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by todstoychev**
Not working with "dev-master" and gives an error while trying composer update

### CODE REVIEW

**Comment by greggilbert** [comment]
Hmm. I just tried this out, and it works fine for me. Given a composer.json of:

```
"require": {
        "greggilbert/recaptcha": "dev-master"
    },
```

It installed the latest version properly:

```
  - Installing greggilbert/recaptcha (dev-master e4e1d7d)
    Cloning e4e1d7d1e379aa37c39e6774be57f535d144e422
```

Updating also worked:

```
$ composer update greggilbert/recaptcha
Loading composer repositories with package information
Updating dependencies (including require-dev)
Generating autoload files
```

What's the error you're seeing?

**Comment by todstoychev** [comment]
Here this is from the console


composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

   Problem 1
     - Conclusion: don't install laravel/framework 4.2.x-dev
     - Conclusion: remove laravel/framework v4.2.16
     - Conclusion: don't install laravel/framework v4.2.16
     - Conclusion: don't install laravel/framework v4.2.15
     - Conclusion: don't install laravel/framework v4.2.14
     - Conclusion: don't install laravel/framework v4.2.13
     - Conclusion: don't install laravel/framework v4.2.12
     - Conclusion: don't install laravel/framework v4.2.11
     - Conclusion: don't install laravel/framework v4.2.10
     - Conclusion: don't install laravel/framework v4.2.9
     - Conclusion: don't install laravel/framework v4.2.8
     - Conclusion: don't install laravel/framework v4.2.7
     - Conclusion: don't install laravel/framework v4.2.6
     - Conclusion: don't install laravel/framework v4.2.5
     - Conclusion: don't install laravel/framework v4.2.4
     - Conclusion: don't install laravel/framework v4.2.3
     - Conclusion: don't install laravel/framework v4.2.2
     - Installation request for greggilbert/recaptcha dev-master -> 
satisfiable by greggilbert/recaptcha[dev-master].
     - Conclusion: don't install laravel/framework v4.2.1
     - Conclusion: don't install laravel/framework v4.2.0
     - greggilbert/recaptcha dev-master requires illuminate/support 
5.0.* -> satisfiable by laravel/framework[5.0.x-dev], 
illuminate/support[5.0.x-dev, v5.0.0].
     - Can only install one of: laravel/framework[v4.2.0-BETA1, 5.0.x-dev].
     - don't install illuminate/support 5.0.x-dev|don't install 
laravel/framework v4.2.0-BETA1
     - don't install illuminate/support v5.0.0|don't install 
laravel/framework v4.2.0-BETA1
     - Installation request for laravel/framework 4.2.* -> satisfiable 
by laravel/framework[4.2.x-dev, v4.2.0, v4.2.0-BETA1, v4.2.1, v4.2.10, 
v4.2.11, v4.2.12, v4.2.13, v4.2.14, v4.2.15, v4.2.16, v4.2.2, v4.2.3, 
v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9].

**Comment by greggilbert** [comment]
dev-master is for L5. If you're looking for L4, try this:

```
"greggilbert/recaptcha": "1.*"
```

**Comment by todstoychev** [comment]
Thanks for the support.

**Pull request closed without merging**
