### PR TITLE
fix illuminate/support error

### PR DESCRIPTION
**Pull request by mohamed-akef**

### CODE REVIEW

**Comment by greggilbert** [comment]
FYI, I undid this. `~5.1` means >= 5.1, < 6.0. Also `~5.1.*` doesn't pass Packagist.

**Comment by mohamed-akef** [comment]
i get this error in laravel 5.0
 - greggilbert/recaptcha dev-master requires illuminate/support ~5.1 -> satisfiable by illuminate/support[v5.1.1].

**Comment by greggilbert** [comment]
Yes, I updated this for 5.1. If you want to use 5.0, try `2.0.x`.

**Comment by mohamed-akef** [comment]
how can i use it ?

**Pull request merged**
