### PR TITLE
Fix issue with textarea in noscript tag and remove unused files and folders

### PR DESCRIPTION
**Pull request by peterpan666**
I had an issue with the content of the noscript tag.

Because there was a line return before the closing textarea tag, there was 4 spaces added so when I paste the key from Google it failed.

Just removing the line return solved the problem.

I also remove some other .gitkeep in unused folders and in views.

### CODE REVIEW

**Comment by greggilbert** [comment]
Why did you remove the migrations?

**Comment by peterpan666** [comment]
Don't really know if this is needed since there is no migrations...

**Comment by greggilbert** [comment]
PR conflicts. Care to rebase and get it to pass?

**Comment by peterpan666** [comment]
Ok I'll try to take a look soon

**Pull request closed without merging**
