### PR TITLE
Allow multiple reCaptchas on single page

### PR DESCRIPTION
**Pull request by Rikcon**
Hello everyone, tweaked this package a bit to allow multiple captchas on single page.
Earlier google's js file was loaded every time i call Recaptcha::render(), now it loads only once and initialize all captchas via callback.

Code may be a little bit smelly but gets the job done.

I'm open for any type of suggestions/contribtions to my work.

### CODE REVIEW

**Comment by greggilbert** [comment]
Couple of things:

1. The `.idea` in the `.gitignore` is unnecessary for this.
2. Can you squash the commits together?

**Comment by Rikcon** [comment]
First time making pull request, i'll see what i can do )

**Comment by Rikcon** [comment]
Is this ok ?

**Comment by DevparkBartekg** [comment]
Hi @greggilbert 
Will it be merged?

**Pull request closed without merging**
